title: Yuki Kusanagi
email: yuki.kusanagi@tuta.io
description: "草薙有希です、だらだら毎日"
baseurl: ""
url: "https://yuki-kusanagi.github.io"
twitter_username: yukihime93
github_username:  yuki-kusanagi
markdown: kramdown
theme: jekyll-swiss
theme_color: yellow
plugins:
  - jekyll-feed
