title: Yuki Kusanagi
email: yuki.kusanagi@tuta.io
description: "草薙有希です、だらだら毎日"
baseurl: ""
url: "https://yuki-kusanagi.github.io"
twitter_username: yukihime93
github_username:  yuki-kusanagi
facebook_username: yuki.kusanagi.161
pixiv_username: yukikusanagi
instagram_username: yukihime93
markdown: kramdown
plugins:
  - jekyll-feed
